### PR TITLE
SearchMatch update fixes complicated 'then' search bugs

### LINKED ISSUE #269: figure search 'then' returning bogus results
This should not be happening. There is only 1 figure between the swing in 3-33-33, not two.
screenshot-2018-1-2 welcome contra

### LINKED ISSUE #461: Search not finding dance that fits
The following search should return You Can't Get There From Here, but doesn't.

We don't understand why!

#figure-query-buffer :

"["then",["or",["figure","form an ocean wave","true","*","*","*","*","*","*"],["figure","form long waves"]],["or",["figure","allemande"],["then",["figure","balance"],["figure","allemande"]]]]"

### PR DESCRIPTION
**Pull request by dcmorse**
resolves #269 
resolves #461 

Introduces sets of SearchMatch objects, which replace arrays of matching figure indexes.

## TODO
- [x] fix datatables bug with all selector
- [x] figure out why it doesn't break on 0-figure dances
- [ ] update wiki

### CODE REVIEW

File: lib/search_match.rb [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+    i = first
+    n = nfigures
+    count.times do
+      yield i
+      i += 1
+      i = 0 if i >= n
+    end
+    self
+  end
+
```
Comment (dcmorse) [inline lib/search_match.rb]: code review here
